[package]
name = "gmux"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1"
crossterm = "0.27"
clap = { version = "4", features = ["derive"] }
dirs = "5"
ratatui = "0.26"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shlex = "1"
